export const gatewayABI = [
    {
        inputs: [
            { internalType: "address", name: "idFactoryAddress", type: "address" },
            { internalType: "address[]", name: "signersToApprove", type: "address[]" },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    { inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }], name: "ExpiredSignature", type: "error" },
    { inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }], name: "RevokedSignature", type: "error" },
    { inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }], name: "SignatureAlreadyRevoked", type: "error" },
    { inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }], name: "SignatureNotRevoked", type: "error" },
    { inputs: [{ internalType: "address", name: "signer", type: "address" }], name: "SignerAlreadyApproved", type: "error" },
    { inputs: [{ internalType: "address", name: "signer", type: "address" }], name: "SignerAlreadyNotApproved", type: "error" },
    { inputs: [], name: "TooManySigners", type: "error" },
    { inputs: [{ internalType: "address", name: "signer", type: "address" }], name: "UnapprovedSigner", type: "error" },
    { inputs: [], name: "ZeroAddress", type: "error" },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: "bytes", name: "signature", type: "bytes" }],
        name: "SignatureApproved",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: "bytes", name: "signature", type: "bytes" }],
        name: "SignatureRevoked",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: "address", name: "signer", type: "address" }],
        name: "SignerApproved",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: "address", name: "signer", type: "address" }],
        name: "SignerRevoked",
        type: "event",
    },
    {
        inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }],
        name: "approveSignature",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "signer", type: "address" }],
        name: "approveSigner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "approvedSigners",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
        name: "callFactory",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "identityOwner", type: "address" }],
        name: "deployIdentityForWallet",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "identityOwner", type: "address" },
            { internalType: "string", name: "salt", type: "string" },
            { internalType: "uint256", name: "signatureExpiry", type: "uint256" },
            { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        name: "deployIdentityWithSalt",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "identityOwner", type: "address" },
            { internalType: "string", name: "salt", type: "string" },
            { internalType: "bytes32[]", name: "managementKeys", type: "bytes32[]" },
            { internalType: "uint256", name: "signatureExpiry", type: "uint256" },
            { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        name: "deployIdentityWithSaltAndManagementKeys",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "idFactory",
        outputs: [{ internalType: "contract IdFactory", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
    {
        inputs: [{ internalType: "bytes", name: "signature", type: "bytes" }],
        name: "revokeSignature",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "signer", type: "address" }],
        name: "revokeSigner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
        name: "revokedSignatures",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferFactoryOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;
