// AUTO-GENERATED FILE

export default {
  hooks: {
    useALMFarmApprove: () => ({}),
    useALMFarmHarvest: () => ({}),
    useALMFarmStake: () => ({}),
    useALMFarmUnstake: () => ({}),
    useALMFarmingRewardsEarned: () => ({}),
    useAllALMVaults: () => ({}),
    useALMVaultsByPool: () => ({}),
    useAllUserALMAmounts: () => ({}),
    useUserALMVaultsByPool: () => ({}),
    useActiveFarming: () => ({}),
    useClosedFarmings: () => ({}),
    useFarmApprove: () => ({}),
    useFarmCheckApprove: () => ({}),
    useFarmHarvest: () => ({}),
    useFarmHarvestUnclaimed: () => ({}),
    useFarmHarvestAll: () => ({}),
    useFarmStake: () => ({}),
    useFarmUnstake: () => ({}),
    useFarmingAPR: () => ({}),
    useFarmingRewardsEarned: () => ({}),
    usePositionInFarming: () => ({}),
    useUnclaimedRewards: () => ({}),
    useLimitOrderInfo: () => ({}),
    useV3CandidatePools: () => ({}),
    useCommonPools: () => ({}),
    usePropsChanged: () => ({}),
    useSmartRouterBestTrade: () => ({}),
    useSmartRouterCallback: () => ({}),
    useAllGauges: () => ({}),
    useFormattedVotingPools: () => ({}),
    useVeTOKENRewards: () => ({}),
    useVeTOKENs: () => ({}),
    useVotingData: () => ({}),
    useVotingPools: () => ({}),
  },
  components: {
    ALMPositionCard: () => null,
    ALMTag: () => null,
    AddALMLiquidityModal: () => null,
    AddAutomatedLiquidityButton: () => null,
    CreateAutomatedPosition: () => null,
    HarvestAndExitALMFarmingCard: () => null,
    RemoveALMLiquidityModal: () => null,
    AnalyticsPoolPage: () => null,
    AnalyticsTokenPage: () => null,
    DexCharts: () => null,
    TokensList: () => null,
    tokensColumns: () => null,
    TokensTable: () => null,
    TransactionsList: () => null,
    transactionsColumns: () => null,
    TransactionsTable: () => null,
    ActiveFarming: () => null,
    CardInfo: () => null,
    FarmTag: () => null,
    FarmingPositionCard: () => null,
    FarmingPositionImg: () => null,
    HarvestAndExitFarmingCard: () => null,
    SelectPositionFarmModal: () => null,
    UnclaimedRewards: () => null,
    KillLimitOrderModal: () => null,
    LimitOrder: () => null,
    LimitOrderButton: () => null,
    LimitOrdersList: () => null,
    LimitPriceCard: () => null,
    SwapTypeSelector: () => null,
    limitOrderColumns: () => null,
    LimitOrdersTable: () => null,
    SwapRouteModal: () => null,
    ClaimRebaseRewardsButton: () => null,
    ClaimVotingRewardsModal: () => null,
    CreateLockModal: () => null,
    LockSelector: () => null,
    LocksList: () => null,
    LocksTotalStats: () => null,
    Manage: () => null,
    Merge: () => null,
    Split: () => null,
    Transfer: () => null,
    ManageLockModal: () => null,
    LocksTable: () => null,
    VotingPoolsTable: () => null,
    VotingActions: () => null,
    VotingPoolsList: () => null,
    VotingTotalStats: () => null,
  },
  utils: {
    getRewardsCalldata: () => undefined,
    getUnclaimedRewardsCalldata: () => undefined,
    isSameRewards: () => undefined,
    getTimeUntilTimestamp: () => undefined,
    optimizeVotes: () => undefined,
  },
};
