export const rebaseRewardAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "DEFAULT_ADMIN_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DURATION",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "NOTIFY_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "PRECISION",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "UPGRADE_INTERFACE_VERSION",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "_deposit",
        inputs: [
            { name: "_amount", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "_withdraw",
        inputs: [
            { name: "_amount", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "earnedForPeriod",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_token", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "earnedForToken",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_token", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "reward", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "earnedForTokenId",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "rewardList", type: "uint256[]", internalType: "uint256[]" },
            { name: "tokenList", type: "address[]", internalType: "address[]" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCurrentPeriod",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRewardForOwner",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getRewardForPeriod",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_token", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getRewardForTokenId",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getRewardList",
        inputs: [],
        outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleAdmin",
        inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "grantNotifyRole",
        inputs: [{ name: "_account", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "grantRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "hasRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "incentivize",
        inputs: [
            { name: "_token", type: "address", internalType: "address" },
            { name: "_amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_voter", type: "address", internalType: "address" },
            { name: "_veTOKEN", type: "address", internalType: "address" },
            { name: "_initialOwner", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "notifyRewardAmount",
        inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "notifyRewardAmount",
        inputs: [
            { name: "_token", type: "address", internalType: "address" },
            { name: "_amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "pendingOwner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "periodInit",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "proxiableUUID",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "renounceRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "callerConfirmation", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "rewardForPeriod",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_reward", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "token",
        inputs: [],
        outputs: [{ name: "_token", type: "address", internalType: "contract IERC20" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenIdRewardClaimedInPeriod",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_reward", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenIdVotesInPeriod",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "totalVotesInPeriod",
        inputs: [{ name: "_period", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "transferERC20",
        inputs: [{ name: "_token", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transferOwnership",
        inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "upgradeToAndCall",
        inputs: [
            { name: "newImplementation", type: "address", internalType: "address" },
            { name: "data", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "payable",
    },
    {
        type: "function",
        name: "veTOKEN",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IVotingEscrow" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "voter",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IVoter" }],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "ClaimReward",
        inputs: [
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_tokenId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_token", type: "address", indexed: false, internalType: "address" },
            { name: "_to", type: "address", indexed: false, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Deposit",
        inputs: [
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_amount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_tokenId", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "IncentivizedReward",
        inputs: [
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_from", type: "address", indexed: false, internalType: "address" },
            { name: "_token", type: "address", indexed: false, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Initialized",
        inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "NotifyReward",
        inputs: [
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_from", type: "address", indexed: false, internalType: "address" },
            { name: "_token", type: "address", indexed: false, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferStarted",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleAdminChanged",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "previousAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "newAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleGranted",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "account", type: "address", indexed: true, internalType: "address" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleRevoked",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "account", type: "address", indexed: true, internalType: "address" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Upgraded",
        inputs: [{ name: "implementation", type: "address", indexed: true, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Withdraw",
        inputs: [
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_amount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_tokenId", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
    {
        type: "error",
        name: "AccessControlUnauthorizedAccount",
        inputs: [
            { name: "account", type: "address", internalType: "address" },
            { name: "neededRole", type: "bytes32", internalType: "bytes32" },
        ],
    },
    { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "ERC1967InvalidImplementation",
        inputs: [{ name: "implementation", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ERC1967NonPayable", inputs: [] },
    { type: "error", name: "FailedCall", inputs: [] },
    { type: "error", name: "FuturePeriodNotClaimable", inputs: [] },
    { type: "error", name: "InvalidInitialization", inputs: [] },
    { type: "error", name: "NotApprovedOrOwner", inputs: [] },
    { type: "error", name: "NotInitializing", inputs: [] },
    { type: "error", name: "NotTOKEN", inputs: [] },
    { type: "error", name: "NotVoter", inputs: [] },
    { type: "error", name: "NotWhitelistedRewardToken", inputs: [] },
    { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "OwnableUnauthorizedAccount",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
    { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
    {
        type: "error",
        name: "UUPSUnsupportedProxiableUUID",
        inputs: [{ name: "slot", type: "bytes32", internalType: "bytes32" }],
    },
] as const;
