export const voterABI = [
    {
        type: "function",
        name: "AUTHORIZED_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DEFAULT_ADMIN_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DURATION",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "UPGRADE_INTERFACE_VERSION",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "algebraGaugeFactory",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract AlgebraGaugeFactory" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "algebraVaultFactory",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IAlgebraVaultFactory" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkPeriodVoted",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "claimVotingRewardBatch",
        inputs: [
            { name: "_votingRewardList", type: "address[]", internalType: "address[]" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "createAlgebraGauge",
        inputs: [{ name: "_poolAddress", type: "address", internalType: "address" }],
        outputs: [
            { name: "_gauge", type: "address", internalType: "address" },
            { name: "_votingReward", type: "address", internalType: "address" },
        ],
        stateMutability: "nonpayable",
    },
    { type: "function", name: "createGauge", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "distribute",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    { type: "function", name: "distributeAll", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "distributeRange",
        inputs: [
            { name: "_start", type: "uint256", internalType: "uint256" },
            { name: "_amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "epoch0Period",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "gaugeToPool",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCurrentPeriod",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getGauge",
        inputs: [{ name: "_pool", type: "address", internalType: "address" }],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct IVoter.Gauge",
                components: [
                    { name: "gauge", type: "address", internalType: "address" },
                    { name: "isAlgebra", type: "bool", internalType: "bool" },
                    { name: "votingReward", type: "address", internalType: "address" },
                    { name: "isAlive", type: "bool", internalType: "bool" },
                    { name: "vault", type: "address", internalType: "address" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getGaugeList",
        inputs: [],
        outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getPeriodData",
        inputs: [{ name: "_period", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "_globalTotalVotes", type: "uint256", internalType: "uint256" },
            { name: "_gaugeList", type: "address[]", internalType: "address[]" },
            { name: "_gaugeTotalVotesList", type: "uint256[]", internalType: "uint256[]" },
            { name: "_totalEmissions", type: "uint256", internalType: "uint256" },
            {
                name: "_gaugeEmissionsList",
                type: "tuple[]",
                internalType: "struct IVoter.Emissions[]",
                components: [
                    { name: "amount", type: "uint256", internalType: "uint256" },
                    { name: "distributed", type: "bool", internalType: "bool" },
                    { name: "killedDistributed", type: "bool", internalType: "bool" },
                ],
            },
            { name: "_totalClaimedEmissions", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getPoolList",
        inputs: [],
        outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleAdmin",
        inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getTokenIdVotes",
        inputs: [
            { name: "_period", type: "uint256", internalType: "uint256" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            { name: "_tokenIdVotedList", type: "address[]", internalType: "address[]" },
            { name: "_tokenIdVotes", type: "uint256[]", internalType: "uint256[]" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "grantRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "hasRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_veTOKEN", type: "address", internalType: "address" },
            { name: "_initialOwner", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "isAlive",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isGauge",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isWhitelisted",
        inputs: [{ name: "_token", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "killGauge",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "minter",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IMinter" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "notifyRewardAmount",
        inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "pendingOwner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "period",
        inputs: [{ name: "_period", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "globalTotalVotes", type: "uint256", internalType: "uint256" },
            { name: "totalEmissions", type: "uint256", internalType: "uint256" },
            { name: "totalClaimedEmissions", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "proxiableUUID",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "rebaseReward",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IRebaseReward" }],
        stateMutability: "view",
    },
    { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "renounceRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "callerConfirmation", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "reviveGauge",
        inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeRole",
        inputs: [
            { name: "role", type: "bytes32", internalType: "bytes32" },
            { name: "account", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setAlgebraGaugeFactory",
        inputs: [{ name: "_algebraGaugeFactory", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setAlgebraVaultFactory",
        inputs: [{ name: "_algebraVaultFactory", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setMinter",
        inputs: [{ name: "_minter", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setRebaseReward",
        inputs: [{ name: "_rebaseReward", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setTokenStatus",
        inputs: [
            { name: "_token", type: "address", internalType: "address" },
            { name: "_status", type: "bool", internalType: "bool" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setVotingRewardFactory",
        inputs: [{ name: "_votingRewardFactory", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    { type: "function", name: "start", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "token",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "transferOwnership",
        inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "upgradeToAndCall",
        inputs: [
            { name: "newImplementation", type: "address", internalType: "address" },
            { name: "data", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "payable",
    },
    {
        type: "function",
        name: "veTOKEN",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IVotingEscrow" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "vote",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_poolList", type: "address[]", internalType: "address[]" },
            { name: "weightList", type: "uint256[]", internalType: "uint256[]" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "votingRewardFactory",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract VotingRewardFactory" }],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "DistributeAlgebraFees",
        inputs: [
            { name: "_pool", type: "address", indexed: false, internalType: "address" },
            { name: "_amount0", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_amount1", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "DistributeEmissions",
        inputs: [
            { name: "_gauge", type: "address", indexed: false, internalType: "address" },
            { name: "_amount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "GaugeCreated",
        inputs: [
            { name: "_gauge", type: "address", indexed: false, internalType: "address" },
            { name: "_votingReward", type: "address", indexed: false, internalType: "address" },
            { name: "_pool", type: "address", indexed: false, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "GaugeKilled",
        inputs: [{ name: "_gauge", type: "address", indexed: false, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "GaugeRevived",
        inputs: [{ name: "_gauge", type: "address", indexed: false, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Initialized",
        inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferStarted",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleAdminChanged",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "previousAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "newAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleGranted",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "account", type: "address", indexed: true, internalType: "address" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleRevoked",
        inputs: [
            { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "account", type: "address", indexed: true, internalType: "address" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "TokenStatus",
        inputs: [
            { name: "_token", type: "address", indexed: false, internalType: "address" },
            { name: "_status", type: "bool", indexed: false, internalType: "bool" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Upgraded",
        inputs: [{ name: "implementation", type: "address", indexed: true, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Voted",
        inputs: [
            { name: "_tokenId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_votingPower", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_period", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
    {
        type: "error",
        name: "AccessControlUnauthorizedAccount",
        inputs: [
            { name: "account", type: "address", internalType: "address" },
            { name: "neededRole", type: "bytes32", internalType: "bytes32" },
        ],
    },
    { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
    { type: "error", name: "AlreadyVotedForPool", inputs: [] },
    { type: "error", name: "AlreadyVotedInPeriod", inputs: [] },
    {
        type: "error",
        name: "ERC1967InvalidImplementation",
        inputs: [{ name: "implementation", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ERC1967NonPayable", inputs: [] },
    { type: "error", name: "FailedCall", inputs: [] },
    { type: "error", name: "GaugeAlreadyExist", inputs: [] },
    { type: "error", name: "GaugeDead", inputs: [] },
    { type: "error", name: "GaugeDoesNotExist", inputs: [] },
    { type: "error", name: "InvalidInitialization", inputs: [] },
    { type: "error", name: "InvalidParameters", inputs: [] },
    { type: "error", name: "InvalidPeriod", inputs: [] },
    { type: "error", name: "NotApprovedOrOwner", inputs: [] },
    { type: "error", name: "NotInitializing", inputs: [] },
    { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "OwnableUnauthorizedAccount",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
    { type: "error", name: "TokenNotWhitelisted", inputs: [] },
    { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
    {
        type: "error",
        name: "UUPSUnsupportedProxiableUUID",
        inputs: [{ name: "slot", type: "bytes32", internalType: "bytes32" }],
    },
    { type: "error", name: "Unauthorized", inputs: [] },
    { type: "error", name: "ZeroVotes", inputs: [] },
] as const;
