export const votingEscrowABI = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "MAXTIME",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "MULTIPLIER",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "UPGRADE_INTERFACE_VERSION",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "WEEK",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "approve",
        inputs: [
            { name: "to", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "artProxy",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "balanceOf",
        inputs: [{ name: "owner", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "balanceOfNFT",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    { type: "function", name: "checkpoint", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "create_lock",
        inputs: [
            { name: "_value", type: "uint256", internalType: "uint256" },
            { name: "_lock_duration", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "create_lock_for",
        inputs: [
            { name: "_value", type: "uint256", internalType: "uint256" },
            { name: "_lock_duration", type: "uint256", internalType: "uint256" },
            { name: "_to", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "deposit_for",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_value", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "epoch",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getApproved",
        inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "get_last_user_slope",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "int128", internalType: "int128" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "iMAXTIME",
        inputs: [],
        outputs: [{ name: "", type: "int128", internalType: "int128" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "increase_amount",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_value", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "increase_unlock_time",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_lock_duration", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_token", type: "address", internalType: "address" },
            { name: "art_proxy", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "isApprovedForAll",
        inputs: [
            { name: "owner", type: "address", internalType: "address" },
            { name: "operator", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isApprovedOrOwner",
        inputs: [
            { name: "_spender", type: "address", internalType: "address" },
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "locked",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "amount", type: "int128", internalType: "int128" },
            { name: "end", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "merge",
        inputs: [
            { name: "_from", type: "uint256", internalType: "uint256" },
            { name: "_to", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "name",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "ownerOf",
        inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "ownership_change",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "pendingOwner",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "point_history",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "bias", type: "int128", internalType: "int128" },
            { name: "slope", type: "int128", internalType: "int128" },
            { name: "ts", type: "uint256", internalType: "uint256" },
            { name: "blk", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "proxiableUUID",
        inputs: [],
        outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
        stateMutability: "view",
    },
    { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "safeTransferFrom",
        inputs: [
            { name: "from", type: "address", internalType: "address" },
            { name: "to", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "safeTransferFrom",
        inputs: [
            { name: "from", type: "address", internalType: "address" },
            { name: "to", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
            { name: "data", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setApprovalForAll",
        inputs: [
            { name: "operator", type: "address", internalType: "address" },
            { name: "approved", type: "bool", internalType: "bool" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setArtProxy",
        inputs: [{ name: "_proxy", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setVoter",
        inputs: [{ name: "_voter", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "slope_changes",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "int128", internalType: "int128" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "split",
        inputs: [
            { name: "_from", type: "uint256", internalType: "uint256" },
            { name: "_weightList", type: "uint256[]", internalType: "uint256[]" },
        ],
        outputs: [{ name: "tokenIdList", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "supply",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "token",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenByIndex",
        inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenId",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenOfOwnerByIndex",
        inputs: [
            { name: "owner", type: "address", internalType: "address" },
            { name: "index", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenURI",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "totalSupply",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "totalVotingPower",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "transferFrom",
        inputs: [
            { name: "from", type: "address", internalType: "address" },
            { name: "to", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transferOwnership",
        inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "upgradeToAndCall",
        inputs: [
            { name: "newImplementation", type: "address", internalType: "address" },
            { name: "data", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "payable",
    },
    {
        type: "function",
        name: "userPointHistory",
        inputs: [
            { name: "_tokenId", type: "uint256", internalType: "uint256" },
            { name: "_idx", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct IVotingEscrow.Point",
                components: [
                    { name: "bias", type: "int128", internalType: "int128" },
                    { name: "slope", type: "int128", internalType: "int128" },
                    { name: "ts", type: "uint256", internalType: "uint256" },
                    { name: "blk", type: "uint256", internalType: "uint256" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "user_point_epoch",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "voted",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "voter",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "withdraw",
        inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "approved", type: "address", indexed: true, internalType: "address" },
            { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ApprovalForAll",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "operator", type: "address", indexed: true, internalType: "address" },
            { name: "approved", type: "bool", indexed: false, internalType: "bool" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Deposit",
        inputs: [
            { name: "provider", type: "address", indexed: true, internalType: "address" },
            { name: "tokenId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "locktime", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "deposit_type", type: "uint8", indexed: false, internalType: "enum IVotingEscrow.DepositType" },
            { name: "ts", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Initialized",
        inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferStarted",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Split",
        inputs: [
            { name: "_from", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_sender", type: "address", indexed: false, internalType: "address" },
            { name: "_count", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Supply",
        inputs: [
            { name: "prevSupply", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "supply", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { name: "from", type: "address", indexed: true, internalType: "address" },
            { name: "to", type: "address", indexed: true, internalType: "address" },
            { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Upgraded",
        inputs: [{ name: "implementation", type: "address", indexed: true, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Withdraw",
        inputs: [
            { name: "provider", type: "address", indexed: true, internalType: "address" },
            { name: "tokenId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "ts", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "ERC1967InvalidImplementation",
        inputs: [{ name: "implementation", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ERC1967NonPayable", inputs: [] },
    { type: "error", name: "ERC721EnumerableForbiddenBatchMint", inputs: [] },
    {
        type: "error",
        name: "ERC721IncorrectOwner",
        inputs: [
            { name: "sender", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
            { name: "owner", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "ERC721InsufficientApproval",
        inputs: [
            { name: "operator", type: "address", internalType: "address" },
            { name: "tokenId", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidApprover",
        inputs: [{ name: "approver", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "ERC721InvalidOperator",
        inputs: [{ name: "operator", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ERC721InvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "ERC721InvalidReceiver",
        inputs: [{ name: "receiver", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ERC721InvalidSender", inputs: [{ name: "sender", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "ERC721NonexistentToken",
        inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "ERC721OutOfBoundsIndex",
        inputs: [
            { name: "owner", type: "address", internalType: "address" },
            { name: "index", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "FailedCall", inputs: [] },
    { type: "error", name: "Invalid", inputs: [] },
    { type: "error", name: "InvalidInitialization", inputs: [] },
    { type: "error", name: "InvalidParameters", inputs: [] },
    { type: "error", name: "LockExpired", inputs: [] },
    { type: "error", name: "LockNotExist", inputs: [] },
    { type: "error", name: "NotExpired", inputs: [] },
    { type: "error", name: "NotInitializing", inputs: [] },
    { type: "error", name: "NotVoter", inputs: [] },
    { type: "error", name: "OverMaxLockTime", inputs: [] },
    { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
    {
        type: "error",
        name: "OwnableUnauthorizedAccount",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
        type: "error",
        name: "SafeCastOverflowedIntToUint",
        inputs: [{ name: "value", type: "int256", internalType: "int256" }],
    },
    { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
    {
        type: "error",
        name: "UUPSUnsupportedProxiableUUID",
        inputs: [{ name: "slot", type: "bytes32", internalType: "bytes32" }],
    },
    { type: "error", name: "Voted", inputs: [] },
    { type: "error", name: "ZeroSplit", inputs: [] },
] as const;
